[package]
name = "multiplication-karatsuba"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "multiplication-karatsuba"
path = "main.rs"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
anyhow = "1.0.98"
